---
title: "Introduction to Mapping and Spatial Analysis Using R"
author: "Kevin Stierhoff"
date: '`r format(Sys.time(), format = "%F %T", tz = "GMT", usetz = T)`'
output: 
  bookdown::html_document2:
      toc: yes
      toc_float: yes
---

```{r setup, message=F}
# Install and load pacman (library management package)
if (!require("pacman")) install.packages("pacman")

# Install and load required packages from CRAN ---------------------------------
pacman::p_load(tidyverse,grid,gridExtra,pander,flextable,lubridate, knitr,here,
               png,devtools,kableExtra,forcats,jpeg,bookdown,bookdownplus,magick)

# Install and load required packages from Github -------------------------------


# Set default knitr chunk options
knitr::opts_chunk$set(warning = F, message = F, dev = "png", dev.args = list(type = "cairo"))  
```

# Course Motivation and Guiding Principles
This course arose from a brief, 1 h-long R-User Group meeting in 2018, where I presented some things I had learned about mapping and spatial analysis using R. I had long been frustrated that mapping and other GIS-type tasks were the only part of my analysis and writing workflow that existed outside of R. With my desire to move toward more automated and reproducible workflows, it was imperative for me to learn the tools available to accomplish these same tasks in R.

While there are numerous ways to accomplish mapping and spatial analysis tasks using R (e.g., the `sp` package, the [R-ArcGIS Bridge](https://r-arcgis.github.io/)), I'll focus on what seems to be the prevailing workflows and packages used by the leaders in the R community (e.g., Hadley, Edzer Pebesma, etc.), including:

+ Rstudio IDE and Rstudio Projects for anlaysis and organization, respectively 
+ `tidyverse` packages for data manipulation (e.g., `tidyr`, `dplyr`) and visualization (e.g., `ggplot2`) 
+ `sf` package for creation, handling, and manipulation of spatial objects

# Course Structure
The class will be structured into **X** modules:

## A

## B

## C

# Course Requirements
Many of the examples presented require the installation and (sometimes) configuration of specialized packages. I've chosen to rely on the `pacman` package (https://github.com/trinker/pacman) to load required packages, and install or update (if necessary). 

_**Special considerations for Mac users: **_

# Course Materials
All of the course materials are available via Github at https://github.com/kstierhoff/PSAWII-Mapping.

# Valuable Resources
+ The various help pages, vignettes, and articles for the [`sf` package](https://r-spatial.github.io/sf/index.html)
+ [Geocomputation with R](https://geocompr.robinlovelace.net/) book by Lovelace, Nowsad, and Muenchow, for a comprehensive treatment of, well, geocomputation using R
+ [R for Data Science](https://r4ds.had.co.nz/) book by Grolemund and Wickam for a wealth of info on data analysis, relying heavily on Tidyverse packages
